- id: card_01_whelp
  name: Whelp
  description: A small fire creature
  rank: 1
  attack: 4
  hp: 7
  elements: [Fire]
  imagePath: /assets/cards/card_01_whelp.png
  leaderPassive: null

- id: card_02_whelpier
  name: Whelpier
  description: A fiery whelp
  rank: 2
  attack: 6
  hp: 9
  elements: [Fire]
  imagePath: /assets/cards/card_02_whelpier.png
  leaderPassive:
    - description: Deal 1.25x fire dmg
      effect:
        - type: damage
          elements: [Fire]
          multipliers: [1.25]
          targets: [Enemy]

- id: card_03_whelpiest
  name: Whelpiest
  description: Very cute, very fire
  rank: 3
  attack: 10
  hp: 12
  elements: [Fire]
  imagePath: /assets/cards/card_03_whelpiest.png
  leaderPassive:
    - description: Deal 1.75x fire dmg
      effect:
        - type: damage
          elements: [Fire]
          multipliers: [1.75]
          targets: [Enemy]

- id: card_04_slime
  name: Slime
  description: A common slime
  rank: 1
  attack: 2
  hp: 9
  elements: [Water]
  imagePath: /assets/cards/card_04_slime.png
  leaderPassive: null

- id: card_05_slimer
  name: Slimer
  description: A very slimy slime
  rank: 2
  attack: 4
  hp: 11
  elements: [Water, Grass]
  imagePath: /assets/cards/card_05_slimer.png
  leaderPassive:
    - description: Deal 1.25x boss dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Dark, Light]
          multipliers: [1.25, 1.25, 1.25, 1.25, 1.25]
          targets: [Boss]

- id: card_06_slimest
  name: Slimest
  description: More heads, more slime
  rank: 3
  attack: 7
  hp: 15
  elements: [Water, Grass]
  imagePath: /assets/cards/card_06_slimest.png
  leaderPassive:
    - description: Deal 1.5x boss dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Dark, Light]
          multipliers: [1.5, 1.5, 1.5, 1.5, 1.5]
          targets: [Boss]

- id: card_07_wisp
  name: Wisp
  description: A common wisp
  rank: 1
  attack: 3
  hp: 8
  elements: [Grass]
  imagePath: /assets/cards/card_07_wisp.png
  leaderPassive: null

- id: card_08_wispier
  name: Wispier
  description: This wisp looks battle-ready!
  rank: 2
  attack: 5
  hp: 10
  elements: [Grass, Light]
  imagePath: /assets/cards/card_08_wispier.png
  leaderPassive: null

- id: card_09_wispiest
  name: Wispiest
  description: The wispiest of wisps
  rank: 3
  attack: 9
  hp: 13
  elements: [Grass, Light]
  imagePath: /assets/cards/card_09_wispiest.png
  leaderPassive:
    - description: Deals 1.5x grass and light dmg
      effect:
        - type: damage
          elements: [Grass, Light]
          multipliers: [1.5, 1.5]
          targets: [Enemy]

- id: card_10_mutagen
  name: Mutagen
  description: A mysterious substance that can be used to mutate cards.
  rank: 1
  attack: 3
  hp: 8
  elements: [Dark, Light]
  imagePath: /assets/cards/card_10_mutagen.png
  leaderPassive: null

- id: card_11_icy
  name: Icy
  description: A cold and icy creature
  rank: 2
  attack: 5
  hp: 13
  elements: [Water, Dark]
  imagePath: /assets/cards/card_11_icy.png
  leaderPassive: null

- id: card_12_glacier
  name: Glacier
  description: A giant block of angry ice
  rank: 3
  attack: 9
  hp: 17
  elements: [Water, Dark, Light]
  imagePath: /assets/cards/card_12_glacier.png
  leaderPassive:
    - description: Multi-elements cards deal full dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Light, Dark]
          multipliers: [1.33, 1.33, 1.33, 1.33, 1.33]
          targets: [Enemy]

- id: card_13_leafmane
  name: Leafmane
  description: Entity covered in sharp leaves
  rank: 2
  attack: 9
  hp: 14
  elements: [Grass]
  imagePath: /assets/cards/card_13_leafmane.png
  leaderPassive: null

- id: card_14_rootold
  name: Rootold
  description: An awakened root system
  rank: 3
  attack: 20
  hp: 30
  elements: [Grass, Water]
  imagePath: /assets/cards/card_14_rootold.png
  leaderPassive: null

- id: card_15_firebro
  name: Firebro
  description: A fiery bro
  rank: 2
  attack: 12
  hp: 15
  elements: [Fire]
  imagePath: /assets/cards/card_15_firebro.png
  leaderPassive: null

- id: card_16_coregolem
  name: Coregolem
  description: A guardian of the core
  rank: 3
  attack: 26
  hp: 27
  elements: [Fire, Dark]
  imagePath: /assets/cards/card_16_coregolem.png
  leaderPassive: null

- id: card_17_rimescale
  name: Rimescale
  description: Its fire burns cold
  rank: 3
  attack: 30
  hp: 40
  elements: [Water, Dark, Fire]
  imagePath: /assets/cards/card_17_rimescale.png
  leaderPassive: null
