- id: card_01_whelp
  name: Whelp
  description: A small fire creature
  rank: 1
  attack: 4
  hp: 2
  elements: [Fire]
  imagePath: /assets/cards/card_01_whelp.png
  leaderPassive: null

- id: card_02_whelpier
  name: Whelpier
  description: A fiery whelp
  rank: 2
  attack: 6
  hp: 4
  elements: [Fire]
  imagePath: /assets/cards/card_02_whelpier.png
  leaderPassive:
    - description: Deal 1.25x fire dmg
      effect:
        - type: damage
          elements: [Fire]
          multipliers: [1.25]
          targets: [Enemy]

- id: card_03_whelpiest
  name: Whelpiest
  description: Very cute, very fire
  rank: 3
  attack: 10
  hp: 7
  elements: [Fire]
  imagePath: /assets/cards/card_03_whelpiest.png
  leaderPassive:
    - description: Deal 1.5x fire dmg
      effect:
        - type: damage
          elements: [Fire]
          multipliers: [1.5]
          targets: [Enemy]

- id: card_04_slime
  name: Slime
  description: A common slime
  rank: 1
  attack: 2
  hp: 4
  elements: [Water]
  imagePath: /assets/cards/card_04_slime.png
  leaderPassive: null

- id: card_05_slimer
  name: Slimer
  description: A very slimy slime
  rank: 2
  attack: 4
  hp: 6
  elements: [Water, Grass]
  imagePath: /assets/cards/card_05_slimer.png
  leaderPassive:
    - description: Deal 1.25x boss dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Dark, Light]
          multipliers: [1.25, 1.25, 1.25, 1.25, 1.25]
          targets: [Boss]

- id: card_06_slimest
  name: Slimest
  description: More heads, more slime
  rank: 3
  attack: 7
  hp: 10
  elements: [Water, Grass]
  imagePath: /assets/cards/card_06_slimest.png
  leaderPassive:
    - description: Deal 1.5x boss dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Dark, Light]
          multipliers: [1.5, 1.5, 1.5, 1.5, 1.5]
          targets: [Boss]

- id: card_07_wisp
  name: Wisp
  description: A common wisp
  rank: 1
  attack: 3
  hp: 3
  elements: [Grass]
  imagePath: /assets/cards/card_07_wisp.png
  leaderPassive: null

- id: card_08_wispier
  name: Wispier
  description: This wisp looks battle-ready!
  rank: 2
  attack: 5
  hp: 5
  elements: [Grass, Light]
  imagePath: /assets/cards/card_08_wispier.png
  leaderPassive: null

- id: card_09_wispiest
  name: Wispiest
  description: The wispiest of wisps
  rank: 3
  attack: 9
  hp: 8
  elements: [Grass, Light]
  imagePath: /assets/cards/card_09_wispiest.png
  leaderPassive:
    - description: Multi-elements cards deal full dmg
      effect:
        - type: damage
          elements: [Fire, Water, Grass, Light, Dark]
          multipliers: [1.33, 1.33, 1.33, 1.33, 1.33] # base dmg for multi-elements dmg is 0.75; this is 1.33x that ~= 1x total dmg
          targets: [Enemy]

- id: card_10_mutagen
  name: Mutagen
  description: A mysterious substance that can be used to mutate cards.
  rank: 1
  attack: 3
  hp: 3
  elements: [Dark, Light]
  imagePath: /assets/cards/card_10_mutagen.png
  leaderPassive: null
