- id: item_01_healing_potion
  name: Healing Potion
  description: Heals 10 hp.
  imagePath: /assets/items/item_01_healing_potion.png
  elements: [Healing]
  effect:
    - type: heal
      amount: 10
      targets: [Player]

- id: item_02_mutation_scroll_basic
  name: Mutation Scroll (Basic)
  description: Learn to mutate creatures
  imagePath: /assets/items/item_02_mutation_scroll_basic.png

- id: item_03_mutation_scroll_advanced
  name: Mutagen Scroll (Adv)
  description: Teaches you how to perform advanced mutations
  imagePath: /assets/items/item_03_mutation_scroll_advanced.png
