- id: loot_table_common_coins
  entries:
    - item: coin
      chance: 1.0
      amount: [2, 3]
    - item: coin
      chance: 0.3
      amount: [3, 4]

- id: loot_table_uncommon_coins
  entries:
    - item: coin
      chance: 1.0
      amount: [5, 8]
    - item: coin
      chance: 0.1
      amount: [7, 10]

- id: loot_table_common_plovmand
  entries:
    - item: plovmand
      chance: 0.05
      amount: [1, 1]

- id: loot_table_uncommon_plovmand
  entries:
    - item: plovmand
      chance: 0.15
      amount: [1, 2]
