- id: world_01_earth
  name: Earth
  level: Easy
  primaryElement: Fire
  stages: 5
  imagePath: /assets/worlds/world_01_earth.png
- id: world_02_neptune
  name: Neptune
  level: Medium
  primaryElement: Water
  stages: 4
  imagePath: /assets/worlds/world_02_neptune.png
